DROP TABLE IF EXISTS
DROP TABLE IF EXISTS

CREATE TABLE ARTISTS(
  id SERIAL PRIMARY KEY
  name TEXT NOT NULL,
  nationality TEXT NOT NULL
);

CREATE TABLE PAINTINGS(
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  artist_id
);
